<a href="https://colab.research.google.com/github/jainalphin99/Deep-Learning-Use-Cases/blob/main/Fake_news_classifie/Fake_news_classifier_LSTM_and_Bidirectional_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from  google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Kaggle Faker News Classifier Using LSTM- Deep LEarning| Natural Language Processing/train.csv")

In [ ]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [ ]:
df= df.dropna()

In [ ]:
X= df.drop("label",axis=1)
y=df['label']

In [ ]:
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import one_hot

from keras.models import Sequential
from keras.layers import Embedding
from keras.layers import Dense
from keras.layers import LSTM


In [ ]:
## voculabry size
voc_size = 5000

# Data Cleaning


In [ ]:
message = X.copy()
message.reset_index(inplace=True)
message

index  ...                                               text
0          0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1          1  ...  Ever get the feeling your life circles the rou...
2          2  ...  Why the Truth Might Get You Fired October 29, ...
3          3  ...  Videos 15 Civilians Killed In Single US Airstr...
4          4  ...  Print \nAn Iranian woman has been sentenced to...
...      ...  ...                                                ...
18280  20795  ...  Rapper T. I. unloaded on black celebrities who...
18281  20796  ...  When the Green Bay Packers lost to the Washing...
18282  20797  ...  The Macy’s of today grew from the union of sev...
18283  20798  ...  NATO, Russia To Hold Parallel Exercises In Bal...
18284  20799  ...    David Swanson is an author, activist, journa...

[18285 rows x 5 columns]

In [ ]:
import re
import nltk
from nltk.corpus import stopwords

from nltk.stem.porter import PorterStemmer

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
### Dataset Preprocessing
corpus =[]
ps_stem =PorterStemmer()
for i in range(0,len(message)):
  review = re.sub('[^a-zA-Z]',' ',message['title'][i])
  review = review.lower()
  review = review.split()

  review = [ps_stem.stem(word) for word in review if word not in stopwords.words("english")]
  review= ' '.join(review)
  corpus.append(review)

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

# One Hot Representation


In [ ]:
onehot_rep = [one_hot(words,voc_size) for words in corpus]
onehot_rep

[[1061, 2056, 788, 1464, 4159, 3183, 777, 384, 4921, 4699],
 [4613, 3930, 3182, 1159, 604, 3258, 1465],
 [4286, 1520, 423, 2696],
 [2226, 2532, 729, 2787, 4038, 4643],
 [3692, 604, 1654, 4435, 3302, 4504, 604, 345, 3074, 1867],
 [763,
  4939,
  4461,
  2085,
  3188,
  1946,
  1843,
  729,
  4121,
  819,
  4026,
  69,
  3523,
  3894,
  1465],
 [4609, 3900, 2461, 3880, 4498, 2175, 2084, 4592, 3577, 2860, 3510],
 [3111, 4792, 3820, 4949, 1466, 2884, 1946, 2126, 3577, 2860, 3510],
 [792, 2417, 2277, 4443, 7, 1695, 4264, 3688, 1946, 1630],
 [4885, 1091, 1139, 2621, 103, 2099, 1865, 3705],
 [3084, 884, 1403, 4989, 4056, 35, 2975, 3966, 4039, 3307, 3489],
 [2787, 2007, 4159, 1695, 1946, 1466],
 [4453, 2809, 2344, 1037, 2599, 4207, 2934, 4282, 3202],
 [3100, 2686, 49, 340, 4219, 2824, 3140, 3577, 2860, 3510],
 [492, 2193, 1254, 3221, 804, 3577, 2860, 3510],
 [4009, 4341, 4520, 4417, 2393, 4627, 2687, 27, 3945, 4848],
 [3089, 944, 3930],
 [2778, 4207, 1929, 3657, 1946, 966, 3364, 1465],
 [3050,

In [ ]:
### Padding
sent_length=20
padded_doc = pad_sequences(onehot_rep,maxlen=sent_length,padding="pre")
padded_doc

array([[   0,    0,    0, ...,  384, 4921, 4699],
       [   0,    0,    0, ...,  604, 3258, 1465],
       [   0,    0,    0, ..., 1520,  423, 2696],
       ...,
       [   0,    0,    0, ..., 3577, 2860, 3510],
       [   0,    0,    0, ..., 3183, 4697, 4554],
       [   0,    0,    0, ..., 2985, 4148, 1192]], dtype=int32)

In [ ]:
len(padded_doc[0])

20

In [ ]:
len(padded_doc)

18285

# Readying Model


In [ ]:
#dim -- 3000 x 40
embedded_feature_size=40
model= Sequential()
#will embded the words
model.add(Embedding(voc_size,embedded_feature_size,input_length=sent_length))
model.add(LSTM(100))
#output layer
model.add(Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=['accuracy'])
print(model.summary())

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_6 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
## X and y
len(padded_doc),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final =np.array(padded_doc)
y_final =np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X_final,y_final,test_size=0.33,random_state=42)

# Model Training


In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 2s 11ms/step - loss: 0.3262 - accuracy: 0.8451 - val_loss: 0.1991 - val_accuracy: 0.9153
Epoch 2/10
192/192 [==============================] - 2s 9ms/step - loss: 0.1417 - accuracy: 0.9451 - val_loss: 0.1938 - val_accuracy: 0.9216
Epoch 3/10
192/192 [==============================] - 2s 9ms/step - loss: 0.1039 - accuracy: 0.9607 - val_loss: 0.2339 - val_accuracy: 0.9191
Epoch 4/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0774 - accuracy: 0.9721 - val_loss: 0.2465 - val_accuracy: 0.9158
Epoch 5/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0585 - accuracy: 0.9809 - val_loss: 0.2878 - val_accuracy: 0.9059
Epoch 6/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0438 - accuracy: 0.9865 - val_loss: 0.3469 - val_accuracy: 0.9176
Epoch 7/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0308 - accuracy: 0.9896 - val_loss: 0.3653 - val_accuracy: 0.9170
Epoch

In [ ]:
# under without Dropout

y_pred =model.predict_classes(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3127,  292],
       [ 223, 2393]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9146644573322287

In [ ]:
from tensorflow.keras.layers import Dropout

In [ ]:
#dim -- 3000 x 40
embedded_feature_size=40
model= Sequential()
#will embded the words
model.add(Embedding(voc_size,embedded_feature_size,input_length=sent_length))
model.add(Dropout(0.7))
model.add(LSTM(100))
model.add(Dropout(0.2))
#output layer
model.add(Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=['accuracy'])
print(model.summary())

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_7 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
dropout_4 (Dropout)          (None, 20, 40)            0         
_________________________________________________________________
lstm_7 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dropout_5 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 2s 11ms/step - loss: 0.3655 - accuracy: 0.8180 - val_loss: 0.2109 - val_accuracy: 0.9067
Epoch 2/10
192/192 [==============================] - 2s 9ms/step - loss: 0.1801 - accuracy: 0.9272 - val_loss: 0.1892 - val_accuracy: 0.9168
Epoch 3/10
192/192 [==============================] - 2s 9ms/step - loss: 0.1405 - accuracy: 0.9452 - val_loss: 0.1897 - val_accuracy: 0.9215
Epoch 4/10
192/192 [==============================] - 2s 9ms/step - loss: 0.1256 - accuracy: 0.9527 - val_loss: 0.1917 - val_accuracy: 0.9213
Epoch 5/10
192/192 [==============================] - 2s 9ms/step - loss: 0.1140 - accuracy: 0.9567 - val_loss: 0.2159 - val_accuracy: 0.9205
Epoch 6/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0956 - accuracy: 0.9661 - val_loss: 0.2084 - val_accuracy: 0.9210
Epoch 7/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0911 - accuracy: 0.9668 - val_loss: 0.2247 - val_accuracy: 0.9178
Epoch

In [ ]:
# under without Dropout

y_pred =model.predict_classes(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3056,  363],
       [ 120, 2496]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.91996685998343

In [ ]:
model.save("model.h5")
print("Saved model to disk")

Saved model to disk


# Bi-Directional LSTM RNN

In [ ]:
from keras.layers import Bidirectional
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import one_hot

from keras.models import Sequential
from keras.layers import Embedding
from keras.layers import Dense
from keras.layers import LSTM

In [ ]:
#dim -- 3000 x 40
embedded_feature_size=40
model1= Sequential()
#will embded the words
model1.add(Embedding(voc_size,embedded_feature_size,input_length=sent_length))
model1.add(Dropout(0.7))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.2))
#output layer
model1.add(Dense(1,activation="sigmoid"))
model1.compile(loss="binary_crossentropy",optimizer="adam",metrics=['accuracy'])
print(model1.summary())

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_11 (Embedding)     (None, 20, 40)            200000    
_________________________________________________________________
dropout_10 (Dropout)         (None, 20, 40)            0         
_________________________________________________________________
bidirectional_6 (Bidirection (None, 200)               112800    
_________________________________________________________________
dropout_11 (Dropout)         (None, 200)               0         
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model1.fit(X_train,y_train,epochs=10,batch_size=40,validation_data=(X_test,y_test))

Epoch 1/10
307/307 [==============================] - 4s 13ms/step - loss: 0.2969 - accuracy: 0.8642 - val_loss: 0.2115 - val_accuracy: 0.9138
Epoch 2/10
307/307 [==============================] - 3s 11ms/step - loss: 0.1744 - accuracy: 0.9309 - val_loss: 0.1921 - val_accuracy: 0.9171
Epoch 3/10
307/307 [==============================] - 3s 11ms/step - loss: 0.1410 - accuracy: 0.9438 - val_loss: 0.2220 - val_accuracy: 0.9178
Epoch 4/10
307/307 [==============================] - 3s 11ms/step - loss: 0.1243 - accuracy: 0.9530 - val_loss: 0.2086 - val_accuracy: 0.9175
Epoch 5/10
307/307 [==============================] - 3s 11ms/step - loss: 0.1110 - accuracy: 0.9589 - val_loss: 0.2065 - val_accuracy: 0.9203
Epoch 6/10
307/307 [==============================] - 3s 11ms/step - loss: 0.1006 - accuracy: 0.9607 - val_loss: 0.2157 - val_accuracy: 0.9201
Epoch 7/10
307/307 [==============================] - 3s 11ms/step - loss: 0.0907 - accuracy: 0.9666 - val_loss: 0.2171 - val_accuracy: 0.9200

In [ ]:
model1.predict(X_test)

array([[9.9769491e-01],
       [8.5427760e-05],
       [6.2214546e-03],
       ...,
       [1.9651213e-04],
       [9.8270881e-01],
       [9.4585335e-01]], dtype=float32)

In [ ]:
# under without Dropout

y_pred =model1.predict_classes(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3161,  258],
       [ 248, 2368]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9161557580778791